config/routes.rb
ApwApp::Application.routes.draw do
  resources :applications

  resources :yesnos

  resources :windows

  resources :ratings

  resources :transports

  resources :consumptions

  resources :consumers

  resources :regulatories

  resources :criticalities

  resources :providers

  resources :customers do
      resources :applications
      get 'score', on: :member
  end

  get 'admmin' => 'welcome#index'

  root 'customers#index'

  get 'customers/:id/score' => 'customers#score'

end

app/models/transport.rb
class Transport < ActiveRecord::Base
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :set_transport, only: [:show, :edit, :update, :destroy]

  # GET /transports
  # GET /transports.json
  def index
    @transports = Transport.all
  end

  # GET /transports/1
  # GET /transports/1.json
  def show
  end

  # GET /transports/new
  def new
    @transport = Transport.new
  end

  # GET /transports/1/edit
  def edit
  end

  # POST /transports
  # POST /transports.json
  def create
    @transport = Transport.new(transport_params)

    respond_to do |format|
      if @transport.save
        format.html { redirect_to @transport, notice: 'Transport was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transport }
      else
        format.html { render action: 'new' }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transports/1
  # PATCH/PUT /transports/1.json
  def update
    respond_to do |format|
      if @transport.update(transport_params)
        format.html { redirect_to @transport, notice: 'Transport was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transports/1
  # DELETE /transports/1.json
  def destroy
    @transport.destroy
    respond_to do |format|
      format.html { redirect_to transports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transport
      @transport = Transport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transport_params
      params.require(:transport).permit(:name, :share)
    end
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/views/transports/_form.html.erb
<%= form_for(@transport) do |f| %>
  <% if @transport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transport.errors.count, "error") %> prohibited this transport from being saved:</h2>

      <ul>
      <% @transport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :share %><br>
    <%= f.text_field :share %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transports/edit.html.erb
<h1>Editing transport</h1>

<%= render 'form' %>

<%= link_to 'Show', @transport %> |
<%= link_to 'Back', transports_path %>

app/views/transports/index.html.erb
<h1>Listing transports</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Share</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transports.each do |transport| %>
      <tr>
        <td><%= transport.name %></td>
        <td><%= transport.share %></td>
        <td><%= link_to 'Show', transport %></td>
        <td><%= link_to 'Edit', edit_transport_path(transport) %></td>
        <td><%= link_to 'Destroy', transport, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transport', new_transport_path %>

app/views/transports/new.html.erb
<h1>New transport</h1>

<%= render 'form' %>

<%= link_to 'Back', transports_path %>

app/views/transports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @transport.name %>
</p>

<p>
  <strong>Share:</strong>
  <%= @transport.share %>
</p>

<%= link_to 'Edit', edit_transport_path(@transport) %> |
<%= link_to 'Back', transports_path %>