config/routes.rb
ApwApp::Application.routes.draw do
  resources :applications

  resources :yesnos

  resources :windows

  resources :ratings

  resources :transports

  resources :consumptions

  resources :consumers

  resources :regulatories

  resources :criticalities

  resources :providers

  resources :customers do
      resources :applications
      get 'score', on: :member
  end

  get 'admmin' => 'welcome#index'

  root 'customers#index'

  get 'customers/:id/score' => 'customers#score'

end

app/models/application.rb
class Application < ActiveRecord::Base
    STYLES    = [ "Client/Server", "Legacy", "N-tier", "SOA" ]
    PROVIDERS = [ "3rd party", "Home-grown", "Pre-packaged" ]
    RATING    = [ "VERY LOW", "LOW", "MODERATE", "HIGH", "VERY HIGH" ]
    CONSUMER_TYPES = [ "Customer", "Internal", "Partner", "Internal+Partner"]
    CONSUMPTION_TYPES = [ "API", "Browser", "Fat client", "Mobile APP", "Other", "SSH/Telnet/RDP", "TTY"]
    TRANSPORT_TYPES = ["Internet/IPSec", "Internet/Std", "LAN", "LL/SONET", "MPLS"]
    YES_NO_TYPES = [ "YES", "NO" ]
    REGULATORY_TYPES = [ "FISMA", "HIPAA", "PCI-DSS", "SOX", "NONE", "OTHER"]
    BIZ_CRITICALITY_TYPES = [ "Tier-0", "Tier-1", "Tier-2", "Tier-3", "Tier-4"]
    TIME_WINDOWS = [ "< 3 months", "3-6 months", "6-12 months", "12-24 months", "> 24 months", "NONE"]

    BUCKET_TYPES = [ "TRANSITION", "TRANSFORMATION", "DEEP DIVE", "SPECIAL HANDLING", "OUT OF SCOPE", "NONE" ]
    PHASE_TYPES = [ "PHASE 1", "PHASE 2", "PHASE 3", "NONE" ]
    SOLUTION_TYPES = ["NO SOLUTION", "PUBLIC CLOUD", "PRIVATE CLOUD", "HYBRID CLOUD", "MANAGED VIRTUALIZATION", "DEDICATED", "COLO" ]

    validates :customer_id,
      :name,
      :servers,
      :tiers,
      :style,
      :provider,
      :customization,
      :consumer,
      :consumption,
      :transport,
      :integration,
      :inhouse,
      :contracted,
      :criticality,
      :sensitivity,
      :regulatory,
      :constraint, presence: true

    validates_uniqueness_of :name, :scope => :customer_id

    validates :servers, numericality: { only_integer: true }
    validates :tiers, numericality: { only_integer: true }

    validates :name, length: { minimum: 2, maximum: 100 }

    validates_inclusion_of :constraint, :in => Application::TIME_WINDOWS

    validates_inclusion_of :bucket, :in => Application::BUCKET_TYPES
    validates_inclusion_of :phase, :in => Application::PHASE_TYPES
    validates_inclusion_of :solution, :in => Application::SOLUTION_TYPES

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  # GET /applications.csv
  def index
    if params[:customer_id]
        @customer = Customer.find(params[:customer_id])
        #this returns an array
        @applications = Application.find_by_sql("select * from applications where customer_id = " + params[:customer_id].to_s)
    else
        #this returns a relation class
        @applications = Application.all
    end

    respond_to do |format|
        format.html
        # from http://railscasts.com/episodes/362-exporting-csv-and-excel?view=asciicast
        format.csv { render text: to_csv(@applications) }
        # format.csv { send_data @applications.to_csv }
    end

  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application }
      else
        format.html { render action: 'new' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
      if params[:customer_id]
          @customer = Customer.find(params[:customer_id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:customer_id, :name, :servers, :tiers, :style, :provider, :customization, :consumer, :consumption, :transport, :integration, :inhouse, :contracted, :criticality, :sensitivity, :regulatory, :constraint, :bucket, :phase, :solution)
    end

    def to_csv(apps)
        CSV.generate do |csv|
            csv << Application.column_names
            apps.each do |app|
                csv << app.attributes.values_at(*Application.column_names)
            end
        end
    end

end

app/helpers/application_helper.rb
require 'fusioncharts_helper'
require 'jqplotcharts_helper'
include FusionChartsHelper 
module ApplicationHelper

end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application, :html => {:class => "rs-form-horizontal"} ) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div id="wrap">
      <div id="main">
      <h2>Complexity Information</h2>
        <div class="rs-control-group">
          <%= f.label :customer_id,  :class => "rs-control-label" %>
          <div class="rs-controls">
            <%= f.number_field :customer_id %>
          </div>
       </div>

       <div class="rs-control-group">
         <%= f.label :name , :class => "rs-control-label" %>
         <div class="rs-controls">
           <%= f.text_field :name, :class => "rs-input-large"  %>
         </div>
       </div>

       <div class="rs-control-group">
         <%= f.label :servers , :class => "rs-control-label" %>
         <div class="rs-controls">
           <%= f.number_field :servers, :class => "rs-input-small" %>
         </div>
       </div>

       <div class="rs-control-group">
         <%= f.label :tiers , :class => "rs-control-label" %>
         <div class="rs-controls">
           <%= f.number_field :tiers , :class => "rs-input-small" %>
         </div>
       </div>

       <div class="rs-control-group">
         <%= f.label :style , :class => "rs-control-label" %>
         <div class="rs-controls">
           <%= f.select :style , Application::STYLES %>
         </div>
       </div>

       <div class="rs-control-group">
         <%= f.label :provider, :class => "rs-control-label" %>
         <div class="rs-controls">
           <%= f.select :provider, Application::PROVIDERS %>
         </div>
       </div>

       <div class="rs-control-group">
         <%= f.label :customization, :class => "rs-control-label" %>
         <div class="rs-controls">
           <%= f.select :customization, Application::RATING %>
         </div>
       </div>

       <div class="rs-control-group">
    <%= f.label :consumer, :class => "rs-control-label"  %>
         <div class="rs-controls">
    <%= f.select :consumer, Application::CONSUMER_TYPES %>
  </div>
  </div>

  <div class="rs-control-group">
    <%= f.label :consumption, :class => "rs-control-label" %>
         <div class="rs-controls">
    <%= f.select :consumption, Application::CONSUMPTION_TYPES %>
  </div>
  </div>

  <div class="rs-control-group">
    <%= f.label :transport , :class => "rs-control-label"%>
         <div class="rs-controls">
    <%= f.select :transport, Application::TRANSPORT_TYPES %>
  </div>
  </div>
  <div class="rs-control-group">
    <%= f.label :integration, :class => "rs-control-label" %>
         <div class="rs-controls">
    <%= f.select :integration, Application::RATING %>
  </div>
  </div>

  <div class="rs-control-group">
    <%= f.label :inhouse , :class => "rs-control-label" %>
         <div class="rs-controls">
    <%= f.select :inhouse, Application::YES_NO_TYPES %>
  </div>
  </div>
  <div class="rs-control-group">
    <%= f.label :contracted , :class => "rs-control-label" %>
         <div class="rs-controls">
    <%= f.select :contracted, Application::YES_NO_TYPES %>
  </div>
  </div>
  </div>

  <div id="sidebar">

    <div>   
      <h2>Risk Information</h2>
      <div class="rs-control-group">
        <%= f.label :criticality , :class => "rs-control-label" %>
        <div class="rs-controls">
          <%= f.select :criticality, Application::BIZ_CRITICALITY_TYPES %>
        </div>
      </div>

      <div class="rs-control-group">
        <%= f.label :sensitivity , :class => "rs-control-label" %>
        <div class="rs-controls">
          <%= f.select :sensitivity, Application::RATING %>
        </div>
      </div>

      <div class="rs-control-group">
        <%= f.label :regulatory, :class => "rs-control-label" %>
        <div class="rs-controls">
          <%= f.select :regulatory, Application::REGULATORY_TYPES %>
        </div>
      </div>

      <div class="rs-control-group">
        <%= f.label :constraint , :class => "rs-control-label" %>
        <div class="rs-controls">
          <%= f.select :constraint, Application::TIME_WINDOWS %>
        </div>
      </div>
    </div>
  </div>


  <div id="sidebar2">
    <div>
      <h2>Assessment Information</h2>
      <div class="rs-control-group">
        <%= f.label :bucket , :class => "rs-control-label" %>
        <div class="rs-controls">
          <%= f.select :bucket, Application::BUCKET_TYPES %>
        </div>
      </div>
      <div class="rs-control-group">
        <%= f.label :phase , :class => "rs-control-label" %>
        <div class="rs-controls">
          <%= f.select :phase, Application::PHASE_TYPES %>
        </div>
      </div>
      <div class="rs-control-group">
        <%= f.label :solution , :class => "rs-control-label" %>
        <div class="rs-controls">
          <%= f.select :solution, Application::SOLUTION_TYPES %>
        </div>
      </div>

    </div>

  </div>

  <div id="footer">
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>

  </div>

<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<%= link_to 'Add Application', new_application_path, :class => "rs-btn rs-primary" %>

<% if @customer
%>

    <%= link_to 'Export to CSV', customer_applications_path(@customer, :format => "csv" ), :class => "rs-btn rs-primary" %>
    <span>&nbsp;&nbsp;&nbsp;</span>
    <%= link_to 'Score', score_customer_path(@customer), :class => "rs-link" %>
    <br />
    <br />
    <h1>Listing applications for customer <%= @customer.name %></h1>
<%else%>
    <br />
    <br />
    <h1>Listing applications for all customers</h1>
<% end %>

<table id="applications" class="display">
  <thead>
    <tr>
      <th>Actions</th>
      <th>Customer ID</th>
      <th>Name</th>
      <th>Servers</th>
      <th>Tiers</th>
      <th>Style</th>
      <th>Provider</th>
      <th>Customization</th>
      <th>Consumer</th>
      <th>Consumption</th>
      <th>Transport</th>
      <th>Integration</th>
      <th>Inhouse</th>
      <th>Contracted</th>
      <th>Criticality</th>
      <th>Sensitivity</th>
      <th>Regulatory</th>
      <th>Constraint</th>
      <th>Bucket</th>
      <th>Phase</th>
      <th>Solution</th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td>
          <div class="rs-btn-groupx">
            <%= link_to '', edit_application_path(application), :class => "rs-edit" %>
            <span style="width:10px"> </span>
            <%= link_to '', application, method: :delete, :class => "rs-delete", data: { confirm: 'Are you sure?' } %>
          </div>
        </td>
        <td><%= application.customer_id %></td>
        <td><%= link_to application.name, application, :class => "rs-link" %></td>
        <td><%= application.servers %></td>
        <td><%= application.tiers %></td>
        <td><%= application.style %></td>
        <td><%= application.provider %></td>
        <td><%= application.customization %></td>
        <td><%= application.consumer %></td>
        <td><%= application.consumption %></td>
        <td><%= application.transport %></td>
        <td><%= application.integration %></td>
        <td><%= application.inhouse %></td>
        <td><%= application.contracted %></td>
        <td><%= application.criticality %></td>
        <td><%= application.sensitivity %></td>
        <td><%= application.regulatory %></td>
        <td><%= application.constraint %></td>
        <td><%= application.bucket %></td>
        <td><%= application.phase %></td>
        <td><%= application.solution %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br/>

<%= javascript_include_tag "jquery.dataTables.min"%>

<script type="text/javascript">
    var oTable = $('#applications').dataTable( { 
        "sScrollX": "800px",
        "sScrollY": "600px",
        "bScrollCollapse" : true
    });
</script>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @application.customer_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @application.name %>
</p>

<p>
  <strong>Servers:</strong>
  <%= @application.servers %>
</p>

<p>
  <strong>Tiers:</strong>
  <%= @application.tiers %>
</p>

<p>
  <strong>Style:</strong>
  <%= @application.style %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @application.provider %>
</p>

<p>
  <strong>Customization:</strong>
  <%= @application.customization %>
</p>

<p>
  <strong>Consumer:</strong>
  <%= @application.consumer %>
</p>

<p>
  <strong>Consumption:</strong>
  <%= @application.consumption %>
</p>

<p>
  <strong>Transport:</strong>
  <%= @application.transport %>
</p>

<p>
  <strong>Integration:</strong>
  <%= @application.integration %>
</p>

<p>
  <strong>Inhouse:</strong>
  <%= @application.inhouse %>
</p>

<p>
  <strong>Contracted:</strong>
  <%= @application.contracted %>
</p>

<p>
  <strong>Criticality:</strong>
  <%= @application.criticality %>
</p>

<p>
  <strong>Sensitivity:</strong>
  <%= @application.sensitivity %>
</p>

<p>
  <strong>Regulatory:</strong>
  <%= @application.regulatory %>
</p>

<p>
  <strong>Constraint:</strong>
  <%= @application.constraint %>
</p>

<p>
  <strong>Bucket:</strong>
  <%= @application.bucket %>
</p>

<p>
  <strong>Phase:</strong>
  <%= @application.phase %>
</p>

<p>
  <strong>Solution:</strong>
  <%= @application.solution %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<% if @customer 
       puts "Found customer"
       puts @customer
   else
       puts "No customer FOUND"
   end
%>
<% if @customer %>
    <%= link_to 'Back', customer_applications_path(@customer) %>
<% else %>
    <%= link_to 'Back', applications_path %>
<% end %>