config/routes.rb
ApwApp::Application.routes.draw do
  resources :applications

  resources :yesnos

  resources :windows

  resources :ratings

  resources :transports

  resources :consumptions

  resources :consumers

  resources :regulatories

  resources :criticalities

  resources :providers

  resources :customers do
      resources :applications
      get 'score', on: :member
  end

  get 'admmin' => 'welcome#index'

  root 'customers#index'

  get 'customers/:id/score' => 'customers#score'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
    has_many :applications
end

app/controllers/customers_controller.rb
require "apw"
require 'html_helper'
include HTMLHelper 
require 'jqplotcharts_helper'
include JQPlotChartsHelper 

class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  # GET /customers/:id/score
  def score
  
      def nvl(v)
          return v ? v : "UNKNOWN"
      end

      set_customer
      puts @customer
      applications = Application.find_by_sql("select * from applications where customer_id = " + @customer.id.to_s() + " order by id asc")
      @complexity_scores = {}
      @risk_scores = {}
      @assessments = {}
      applications.each { |a|
          @complexity_scores[a.name] =   complexityScores(a.servers.to_i, a.tiers.to_i, a.style, a.provider, a.customization, a.consumer, a.consumption, a.transport, a.integration, a.inhouse, a.contracted)
          @risk_scores[a.name] =  riskScores(a.criticality, a.sensitivity, a.regulatory, a.constraint)
          @assessments[a.name] = {'bucket' =>  nvl(a.bucket), 'phase' => nvl(a.phase), 'solution' => nvl(a.solution) }
      }
      puts @complexity_scores
      puts @risk_scores
      names_array = []
      bar_data = []
      @complexity_scores.each do |app_name, complexities|
          names_array << app_name
          bar_data << complexities['totallComplexity']
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table style="width:30%" class="rs-list-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Applications</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.name, customer, :class => "rs-link" %></td>
        <td><%= link_to 'Applications', customer_applications_url(customer), :class => "rs-link" %></td>
        <td>
          <div class="rs-btn-group">
            <%= link_to '', edit_customer_path(customer), :class => "rs-edit" %>
            <span>&nbsp;&nbsp;&nbsp;</span>
            <%= link_to 'Delete', customer, method: :delete, data: { confirm: 'Are you sure?' }  %>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="rs-btn-group">
  <%= link_to 'New Customer', new_customer_path, :class => "rs-btn rs-btn-primary" %>
</div>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/score.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer Name:</strong>
  <%= link_to @customer.name, customer_path(@customer) %>
  <span>&nbsp;&nbsp;&nbsp;</span>
  <%= link_to 'Applications', customer_applications_path(@customer) %>
</p>


<%= javascript_include_tag "jquery.jqplot.min"%>
<%= javascript_include_tag "jqplot.barRenderer.min"%>
<%= javascript_include_tag "jqplot.categoryAxisRenderer.min"%>
<%= javascript_include_tag "jqplot.canvasTextRenderer.min" %>
<%= javascript_include_tag "jqplot.canvasAxisTickRenderer.min" %>
<%= javascript_include_tag "jqplot.pointLabels.min"%>
<%= javascript_include_tag "jqplot.dateAxisRenderer.min"%>
<%= javascript_include_tag "canvas2image"%>
<%= javascript_include_tag "jqplot.bubbleRenderer.min"%>
<%= javascript_include_tag "jqplot.cursor.min"%>
<%= javascript_include_tag "excanvas"%>
<%= javascript_include_tag "jqplot.pieRenderer.min"%>
<%= javascript_include_tag "jqplot.pointLabels.min"%>
<%= javascript_include_tag "jqplot.canvasAxisLabelRenderer.min"%>
<%= javascript_include_tag "jqplot.highlighter.min"%>
<%= javascript_include_tag "jquery-ui"%>
<%= javascript_include_tag "jquery.dataTables.min"%>


<div id="tabs">
    <ul>
        <li><a href="#tabs-1">Score</a></li>
        <li><a href="#tabs-2">Risk</a></li>
        <li><a href="#tabs-3">Complexity</a></li>
        <li><a href="#tabs-4">Risk vs Complexity</a></li>
        <li><a href="#tabs-5">Buckets</a></li>
        <li><a href="#tabs-6">Phases</a></li>
        <li><a href="#tabs-7">Solution</a></li>
    </ul>
    <div id="tabs-1">
<table id="applications" class="display">
    <thead>
        <tr>
            <th>Application</th>
            <th>Servers</th>
            <th>Tiers</th>
            <th>Arch Style</th>
            <th>Provider</th>
            <th>Customization</th>
            <th>Consumer</th>
            <th>Consumption</th>
            <th>Transport</th>
            <th>Integration</th>
            <th>In-House</th>
            <th>Extrernally Contracted</th>
            <th>Total Complexity Score</th>
            <th> </th>
            <th>Biz Criticality</th>
            <th>Data Sensitivity</th>
            <th>Regulatory</th>
            <th>Constraint</th>
            <th>Total Risk Score</th>
        </tr>
    </thead>
<%

    def update(h, k) 
        if h.has_key?(k)
            h[k] += 1
        else
            h[k] = 1
        end
        return h
    end

    def add(h, k, v)
        if not h.has_key?(k)
            h[k] = []
        end
        h[k] << [v]
        return h
    end

    def hash2array(h) 
        a = []
        h.each do |k, v|
            a << [k, v]
        end
        return a
    end

    complexity_data = []
    risk_data = []
    risk_complexity_data = []
    bucket_data = {}
    phase_data = {}
    solution_data = {}

    buckets = {}
    phases = {}
    solutions = {}

    @complexity_scores.each do |name, c|
        complexity_data << [name, c['totalScore']]
        risk_data << [name, @risk_scores[name]['totalScore']]
        risk_complexity_data << [@risk_scores[name]['totalScore'], c['totalScore'], 10, name]
        bkt = @assessments[name]['bucket']
        update(bucket_data, bkt)
        add(buckets, bkt, name)
        update(phase_data, @assessments[name]['phase'])
        add(phases, @assessments[name]['phase'], name)
        update(solution_data, @assessments[name]['solution'])
        add(solutions, @assessments[name]['solution'], name)
%>
    <tr>
        <td><%= name %></td>
        <td><%= c['servers'] %></td>
        <td><%= c['tiers'] %></td>
        <td><%= c['archStyle'] %></td>
        <td><%= c['provider'] %></td>
        <td><%= c['customization'] %></td>
        <td><%= c['consumer'] %></td>
        <td><%= c['consumption'] %></td>
        <td><%= c['transport'] %></td>
        <td><%= c['integration'] %></td>
        <td><%= c['inhouse'] %></td>
        <td><%= c['contracted'] %></td>
        <td><%= c['totalScore'] %></td>
        <td> </td>

        <td><%= @risk_scores[name]['criticality'] %></td>
        <td><%= @risk_scores[name]['sensitivity'] %></td>
        <td><%= @risk_scores[name]['regulatory'] %></td>
        <td><%= @risk_scores[name]['constraint'] %></td>
        <td><%= @risk_scores[name]['totalScore'] %></td>

    </tr>
<% end %>
    </tbody>
</table>

<%
    puts "Printing complexity data"
    puts complexity_data
%>
    </div>
    <div id="tabs-2">
        <% render_jqplot_chart(risk_data, 'Risk', 800, 500)  %>
    </div>
    <div id="tabs-3">
        <% render_jqplot_chart(complexity_data, 'Complexity', 800, 500)  %>
    </div>
    <div id="tabs-4">
        <% render_jqplot_scatter(risk_complexity_data, 'rsk_cplxty', 'Risk vs. Complexity', 'Risk Score', 'Complexity Score', 1000, 800) %>
    </div>
    <div id="tabs-5">
        <% 
           render_jqplot_pie(hash2array(bucket_data), 'Buckets', 700, 500) 
           i = 1
           buckets.each do |bucket, apps|
               render_table("buckets_table_"  + i.to_s , ["Application"], apps, bucket, "display mini")
               i += 1
           end
         %>
    </div>
    <div id="tabs-6">
        <% render_jqplot_pie(hash2array(phase_data), 'Phases', 700, 500) 
           i = 1
           phases.each do |phase, apps|
               render_table("phases_table_" + i.to_s, ["Application"], apps, phase, "display mini")
               i += 1
           end
        %>
    </div>
    <div id="tabs-7">
        <% render_jqplot_pie(hash2array(solution_data), 'Solutions', 700, 500)
           i = 1
           solutions.each do |soln, apps|
               render_table("solutions_table_" + i.to_s, ["Application"], apps, soln, "display mini")
               i += 1
           end
        %>
    </div>
</div>

<script>
    $(function() {
        $( "#tabs" ).tabs();
    });
</script>

<script type="text/javascript">
    var oTable = $('#applications').dataTable( {
        "sScrollX": "800px",
        "sScrollY": "600px",
        "bSort": false,
        "bScrollCollapse" : true
        });
    $("#applications tbody").click(function(event) { 
        $(oTable.fnSettings().aoData).each(function() {
            $(this.nTr).removeClass('row_selected');
        });
        $(event.target.parentNode).addClass('row_selected');
    });

    var sTable = $('table.mini').dataTable( {
        "sScrollX": "300px",
        "sScrollY": "300px",
        "bScrollCollapse" : true,
        "bSort": false,
        "bSearchable": false,
        "bPaginate": false,
        "bFilter": false
        });
</script>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Customer details:</h2>
<p>
  <strong>Name:</strong>
  <%= @customer.name %>
  <br />
  <strong>Customer ID:</strong>
  <%= @customer.id %>
</p>

<hr />
<div style="font-size:14px;">
Manage <%= link_to 'Applications', customer_applications_path(@customer) , :class => "rs-link" %>  for this customer, <br /> <br />
Or check the <%= link_to 'Score', score_customer_path(@customer), :class => "rs-link" %>  for this customer's applications,  <br /> <br/>
Or <%= link_to 'Edit', edit_customer_path(@customer), :class => "rs-link" %> the customer details,  <br /> <br />
Or go <%= link_to 'Back', customers_path , :class => "rs-link"%> to list of customers.
</div>